using System.Text;
using FinancialAdvisor.Models;
using Newtonsoft.Json;

namespace FinancialAdvisor.Services;

public interface IReportWriter
{
    Task<string> WriteReportAsync(string jobId, PortfolioReport report);
}

public class ReportWriter : IReportWriter
{
    private readonly string _outDir;
    private readonly ILogger<ReportWriter> _log;

    public ReportWriter(IConfiguration cfg, ILogger<ReportWriter> log)
    {
        _outDir = cfg["Reports:OutputDirectory"] ?? "./reports";
        _log = log;
    }

    public async Task<string> WriteReportAsync(string jobId, PortfolioReport report)
    {
        var dir = Path.Combine(_outDir, jobId);
        Directory.CreateDirectory(dir);

        await File.WriteAllTextAsync(Path.Combine(dir, "report.json"),
            JsonConvert.SerializeObject(report, Formatting.Indented));

        await File.WriteAllTextAsync(Path.Combine(dir, "report.md"),
            BuildMarkdown(report));

        // Individual ticker reports + agent trace files
        foreach (var sr in report.StockReports)
        {
            await File.WriteAllTextAsync(Path.Combine(dir, $"{sr.Ticker}.md"),
                BuildTickerMd(sr));

            // Agent reasoning traces (the agentic thinking visible here)
            await File.WriteAllTextAsync(Path.Combine(dir, $"{sr.Ticker}_agent_traces.md"),
                BuildTraceMd(sr));
        }

        _log.LogInformation("Reports written: {Dir}", dir);
        return dir;
    }

    // ── Portfolio Report ──────────────────────────────────────────────────

    private static string BuildMarkdown(PortfolioReport report)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# 📊 Multi-Agent Financial Investment Analysis");
        sb.AppendLine($"**Job ID:** `{report.JobId}` | **Generated:** {report.GeneratedAt:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine("## 🎯 Executive Summary");
        sb.AppendLine($"> {report.ExecutiveSummary}");
        sb.AppendLine();
        sb.AppendLine("## 📈 Portfolio Overview");
        sb.AppendLine();
        sb.AppendLine("| Ticker | Action | Confidence | Price | Target | Upside | Risk | Fund. | Sentiment |");
        sb.AppendLine("|--------|--------|-----------|-------|--------|--------|------|-------|-----------|");

        foreach (var s in report.StockReports.OrderByDescending(r => r.Recommendation.Confidence))
        {
            var r = s.Recommendation;
            sb.AppendLine($"| **{r.Ticker}** | {Emoji(r.Action)} {r.Action} | {r.Confidence:F0}% | " +
                $"${r.CurrentPrice:F2} | ${r.PriceTarget:F2} | {r.UpsidePercent:+0.0;-0.0}% | " +
                $"{RiskEmoji(r.RiskLevel)} {r.RiskLevel} | {r.Fundamental.Score:F0}/100 ({r.Fundamental.Grade}) | {r.Sentiment.Overall} |");
        }
        sb.AppendLine();
        sb.AppendLine("---");

        foreach (var sr in report.StockReports)
        {
            sb.Append(BuildTickerSection(sr));
            sb.AppendLine("---");
        }

        sb.AppendLine("> *Generated by Multi-Agent Agentic Financial Advisor — 5 autonomous ReAct agents*");
        sb.AppendLine("> **Not financial advice.**");
        return sb.ToString();
    }

    // ── Individual Ticker ─────────────────────────────────────────────────

    private static string BuildTickerMd(StockReport sr) =>
        $"# {sr.Ticker} — {sr.Recommendation.CompanyName}\n*{sr.GeneratedAt:yyyy-MM-dd HH:mm} UTC*\n\n" +
        BuildTickerSection(sr);

    private static string BuildTickerSection(StockReport sr)
    {
        var r  = sr.Recommendation;
        var sb = new StringBuilder();

        sb.AppendLine($"### {Emoji(r.Action)} {r.Ticker} — {r.Action} | {r.Confidence:F0}% Confidence");
        sb.AppendLine($"**Price:** ${r.CurrentPrice:F2} → **Target:** ${r.PriceTarget:F2} " +
            $"({r.UpsidePercent:+0.0;-0.0}%) | **Horizon:** {r.TimeHorizon} | **Risk:** {RiskEmoji(r.RiskLevel)} {r.RiskLevel}");
        sb.AppendLine();
        sb.AppendLine("#### 🏛️ CIO Investment Memo");
        var cioSummary = r.CIOSummary ?? "";
        sb.AppendLine($"> {cioSummary[..Math.Min(500, cioSummary.Length)]}");
        sb.AppendLine();

        // Agent score cards
        sb.AppendLine("#### 🤖 Agent Score Cards");
        sb.AppendLine("| Agent | Result | Steps |");
        sb.AppendLine("|-------|--------|-------|");
        sb.AppendLine($"| 1️⃣ DataCollection | Collected: {sr.RawData.News.Count} news, {sr.RawData.AnalystRatings.Count} ratings | {sr.AllTraces.FirstOrDefault(t => t.AgentName == "DataCollectionAgent")?.TotalSteps ?? 0} |");
        sb.AppendLine($"| 2️⃣ Fundamental | Score: {r.Fundamental.Score:F0}/100 Grade {r.Fundamental.Grade} | {r.Fundamental.Trace.TotalSteps} |");
        sb.AppendLine($"| 3️⃣ Sentiment | {r.Sentiment.Overall} ({r.Sentiment.Score:+0.00;-0.00}) | {r.Sentiment.Trace.TotalSteps} |");
        sb.AppendLine($"| 4️⃣ Risk | {r.Risk.Level} ({r.Risk.Score:F0}/100) | {r.Risk.Trace.TotalSteps} |");
        sb.AppendLine($"| 5️⃣ CIO | {r.Action} @ {r.Confidence:F0}% confidence | {r.CIOTrace.TotalSteps} |");
        sb.AppendLine();

        // Fundamental
        sb.AppendLine("#### 🔬 Fundamental Analysis");
        sb.AppendLine($"**Score:** {r.Fundamental.Score:F0}/100 | **Grade:** {r.Fundamental.Grade}");
        if (r.Fundamental.Strengths.Any()) { sb.AppendLine("**Strengths:**"); foreach (var s in r.Fundamental.Strengths) sb.AppendLine($"- ✅ {s}"); }
        if (r.Fundamental.Weaknesses.Any()) { sb.AppendLine("**Weaknesses:**"); foreach (var w in r.Fundamental.Weaknesses) sb.AppendLine($"- ❌ {w}"); }
        sb.AppendLine();

        // Sentiment
        sb.AppendLine("#### 📰 Sentiment Analysis");
        sb.AppendLine($"**Overall:** {r.Sentiment.Overall} | **Score:** {r.Sentiment.Score:+0.00;-0.00} | " +
            $"{r.Sentiment.BullishPercent:F0}% Bull / {r.Sentiment.NeutralPercent:F0}% Neutral / {r.Sentiment.BearishPercent:F0}% Bear");
        sb.AppendLine();

        // Risk
        sb.AppendLine("#### ⚠️ Risk Analysis");
        sb.AppendLine($"**Level:** {r.Risk.Level} ({r.Risk.Score:F0}/100)");
        foreach (var rf in r.Risk.RiskFactors.Take(4)) sb.AppendLine($"- 🔴 {rf}");
        sb.AppendLine();

        // Catalysts & Risks
        if (r.KeyCatalysts.Any()) { sb.AppendLine("**Key Catalysts:**"); foreach (var c in r.KeyCatalysts) sb.AppendLine($"- 🚀 {c}"); }
        if (r.KeyRisks.Any()) { sb.AppendLine("**Key Risks:**"); foreach (var kr in r.KeyRisks) sb.AppendLine($"- ⚡ {kr}"); }
        sb.AppendLine();

        // Financial data
        var m = sr.RawData.Metrics;
        sb.AppendLine("#### 💹 Key Metrics");
        sb.AppendLine($"P/E: {m.PERatio:F1} | P/B: {m.PBRatio:F1} | Beta: {m.Beta:F2} | D/E: {m.DebtToEquity:F2} | FCF: ${(double?)(m.FreeCashFlow ?? 0) / 1e9:F1}B");
        sb.AppendLine($"52W: ${m.FiftyTwoWeekLow:F2} – ${m.FiftyTwoWeekHigh:F2} | Sector: {m.Sector}");
        sb.AppendLine();

        return sb.ToString();
    }

    // ── Agent Trace Report (the "thinking" made visible) ─────────────────

    private static string BuildTraceMd(StockReport sr)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# 🧠 Agent Reasoning Traces — {sr.Ticker}");
        sb.AppendLine($"*This file shows exactly how each AI agent reasoned and which tools it called.*");
        sb.AppendLine();

        foreach (var trace in sr.AllTraces)
        {
            sb.AppendLine($"---");
            sb.AppendLine($"## {trace.AgentName}");
            sb.AppendLine($"**Goal:** {(trace.Goal ?? "")[..Math.Min(200, (trace.Goal ?? "").Length)]}");
            sb.AppendLine($"**Steps:** {trace.TotalSteps} | **Succeeded:** {trace.Succeeded}");
            sb.AppendLine();

            foreach (var step in trace.Steps)
            {
                sb.AppendLine($"### Step {step.StepNumber}");
                if (!string.IsNullOrEmpty(step.Thought))
                    sb.AppendLine($"**💭 Thought:** {step.Thought}");

                if (step.IsFinal)
                {
                    var fa = step.FinalAnswer ?? "";
                    sb.AppendLine($"**✅ FINAL ANSWER:** {fa[..Math.Min(400, fa.Length)]}");
                }
                else
                {
                    if (!string.IsNullOrEmpty(step.Action))
                    {
                        var ai = step.ActionInput ?? "";
                        sb.AppendLine($"**🔧 Action:** `{step.Action}` | **Input:** `{ai[..Math.Min(150, ai.Length)]}`");
                    }
                    if (!string.IsNullOrEmpty(step.Observation))
                    {
                        var obs = step.Observation;
                        sb.AppendLine($"**👁️ Observation:** {obs[..Math.Min(300, obs.Length)]}...");
                    }
                }
                sb.AppendLine();
            }
        }
        return sb.ToString();
    }

    private static string Emoji(Models.Action a) => a switch
    {
        Models.Action.StrongBuy  => "🟢", Models.Action.Buy  => "🔵",
        Models.Action.Hold       => "🟡", Models.Action.Sell => "🟠",
        Models.Action.StrongSell => "🔴", _ => "⚪"
    };

    private static string RiskEmoji(RiskLevel r) => r switch
    {
        RiskLevel.Low => "🟢", RiskLevel.Medium => "🟡",
        RiskLevel.High => "🟠", RiskLevel.VeryHigh => "🔴", _ => "⚪"
    };
}
